/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const Character = forwardRef(({ walk, cameraRef }, characterRef) => {
  const { nodes, materials, animations } = useGLTF("/character.gltf");
  const { actions } = useAnimations(animations, characterRef);
  useEffect(() => {
    if (walk) actions.walk.play();
    else actions.walk.stop();
  });
  return (
    <group
      ref={characterRef}
      dispose={null}
      rotation={cameraRef.current.rotation}
    >
      <group>
        <group position={[4.08, 5.9, -1.01]} rotation={[1.89, 0.88, -2.05]} />
        <group position={[7.36, 4.96, 6.93]} rotation={[1.24, 0.33, -0.76]} />
        <group rotation={[Math.PI / 2, 0, Math.PI]} scale={0.05}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            geometry={nodes.Beta_Joints.geometry}
            material={materials.Beta_Joints_MAT}
            skeleton={nodes.Beta_Joints.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Beta_Surface.geometry}
            material={materials["asdf1:Beta_HighLimbsGeoSG2"]}
            skeleton={nodes.Beta_Surface.skeleton}
          />
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/character.gltf");

export default Character;
