/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GSMRF (https://sketchfab.com/gsmrf)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/standing-greeting-70abd22b5e3b418e8218680e44c21fce
title: Standing Greeting
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Shopkeeper({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/shopkeeper/scene.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["mixamo.com"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group>
              <group>
                <group
                  position={[0, 949.87, -612.38]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={100}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group position={[0, 949.87, -612.38]} scale={100}>
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group
                  position={[0, 949.87, -612.38]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={100}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group
                  position={[0, 949.87, -612.38]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={100}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group
                  position={[0, 949.87, -612.38]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group
                  position={[0, 949.87, -612.38]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  position={[0, -972.88, 2303.52]}
                  rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                  scale={5550.13}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group
                  position={[0, -972.88, 2303.52]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={5550.13}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group
                  position={[0, 872.34, 2344]}
                  rotation={[0, 1.57, 0]}
                  scale={100}
                >
                  <group />
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group>
                    <primitive object={nodes._rootJoint} />
                    <group rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh
                      geometry={nodes.Object_93.geometry}
                      material={materials.material_0}
                      skeleton={nodes.Object_93.skeleton}
                    />
                    <skinnedMesh
                      geometry={nodes.Object_94.geometry}
                      material={materials.Body_2}
                      skeleton={nodes.Object_94.skeleton}
                    />
                    <skinnedMesh
                      geometry={nodes.Object_95.geometry}
                      material={materials.Body_3}
                      skeleton={nodes.Object_95.skeleton}
                    />
                  </group>
                </group>
                <group rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group
                  position={[0, -972.88, 2303.52]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={5550.13}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
                <group
                  position={[0, -972.88, 2303.52]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={5550.13}
                >
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shopkeeper/scene.gltf");
