/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Wave({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/wave/source/wave.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Animation"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.hips001} dispose={null} />
      <skinnedMesh
        name="Cube001"
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        skeleton={nodes.Cube001.skeleton}
        morphTargetDictionary={nodes.Cube001.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube001.morphTargetInfluences}
      />
      <group>
        <skinnedMesh
          name="Cube_1"
          geometry={nodes.Cube_1.geometry}
          material={materials.skin}
          skeleton={nodes.Cube_1.skeleton}
          morphTargetDictionary={nodes.Cube_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube_1.morphTargetInfluences}
        />
        <skinnedMesh
          name="Cube_2"
          geometry={nodes.Cube_2.geometry}
          material={materials.black}
          skeleton={nodes.Cube_2.skeleton}
          morphTargetDictionary={nodes.Cube_2.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube_2.morphTargetInfluences}
        />
        <skinnedMesh
          name="Cube_3"
          geometry={nodes.Cube_3.geometry}
          material={materials.blue_cloth}
          skeleton={nodes.Cube_3.skeleton}
          morphTargetDictionary={nodes.Cube_3.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube_3.morphTargetInfluences}
        />
        <skinnedMesh
          name="Cube_4"
          geometry={nodes.Cube_4.geometry}
          material={nodes.Cube_4.material}
          skeleton={nodes.Cube_4.skeleton}
          morphTargetDictionary={nodes.Cube_4.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube_4.morphTargetInfluences}
        />
        <skinnedMesh
          name="Cube_5"
          geometry={nodes.Cube_5.geometry}
          material={materials.shoe}
          skeleton={nodes.Cube_5.skeleton}
          morphTargetDictionary={nodes.Cube_5.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube_5.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/wave/source/wave.gltf");
